
import { Children } from "react";
import "./globals.css";

export const metadata = {
  title: "Next.js Kanban",
  description: "Generated by Team 6 FE",
};

export default function RootLayout({ children }) {


  return (
    <html>
      {Children}
    </html>
  );
}
