import "./globals.css";

export const metadata = {
  title: "::kanban::",
  description: "Generated by Team 6 FE",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
